version: "3.4"
services:
  nginx:
    image: nginx
    volumes: 
      - ./nginx:/etc/nginx/conf.d:ro
      - ./default:/var/www/default:ro
    ports:
      - "80:80"
    links:
      - php
  php:
    image: php:7.2-fpm
    volumes:
      - ./default:/var/www/default:ro